[theme]
primaryColor      = "#8b55d8"   # roxo — cor do slider, radio buttons, checkboxes
backgroundColor   = "#ffffff"
secondaryBackgroundColor = "#f4f6f9"
textColor         = "#0d3145"   # azul escuro
font              = "sans serif"
